export const STORE_BREAD_CRUMBS = 'STORE_BREAD_CRUMBS'

export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES'
export const PAGES_LOADED = 'PAGES_LOADED'

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS'
export const STORE_FETCHED_POST = 'STORE_FETCHED_POST'
export const POSTS_LOADED = 'POSTS_LOADED'
export const STORE_POSTS_TOTAL_PAGES = 'STORE_POSTS_TOTAL_PAGES'
export const STORE_POSTS_CURRENT_PAGE = 'STORE_POSTS_CURRENT_PAGE'

export const STORE_FETCHED_TAGS = 'STORE_FETCHED_TAGS'
export const STORE_FETCHED_TAG = 'STORE_FETCHED_TAG'
export const TAGS_LOADED = 'TAGS_LOADED'

export const STORE_FETCHED_MENU = 'STORE_FETCHED_MENU'
export const MENU_LOADED = 'MENU_LOADED'

export const STORE_FETCHED_USERS = 'STORE_FETCHED_USERS'
export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const USERS_LOADED = 'USERS_LOADED'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'

export const STORE_FETCHED_CATEGORY_ID = 'STORE_FETCHED_CATEGORY_ID'
export const CATEGORY_LOADED = 'CATEGORY_LOADED'
