export const STORE_BREAD_CRUMBS = 'STORE_BREAD_CRUMBS'

export const STORE_FETCHED_SITE_INFO = 'STORE_FETCHED_SITE_INFO'
export const SITE_INFO_LOADED = 'SITE_INFO_LOADED'

export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES'
export const PAGES_LOADED = 'PAGES_LOADED'

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS'
export const STORE_FETCHED_POST = 'STORE_FETCHED_POST'
export const POSTS_LOADED = 'POSTS_LOADED'
export const STORE_POSTS_TOTAL_PAGES = 'STORE_POSTS_TOTAL_PAGES'
export const STORE_POSTS_CURRENT_PAGE = 'STORE_POSTS_CURRENT_PAGE'
export const STORE_FETCHED_RELATED_POSTS = 'STORE_FETCHED_RELATED_POSTS'
export const RELATED_POSTS_LOADED = 'RELATED_POSTS_LOADED'
export const STORE_FETCHED_POPULAR_POSTS = 'STORE_FETCHED_POPULAR_POSTS'
export const POPULAR_POSTS_LOADED = 'POPULAR_POSTS_LOADED'

export const STORE_FETCHED_PAGE = 'STORE_FETCHED_PAGE'
export const PAGE_LOADED = 'PAGE_LOADED'

export const STORE_FETCHED_TAGS = 'STORE_FETCHED_TAGS'
export const STORE_FETCHED_TAG = 'STORE_FETCHED_TAG'
export const TAGS_LOADED = 'TAGS_LOADED'

export const STORE_FETCHED_MENU = 'STORE_FETCHED_MENU'
export const MENU_LOADED = 'MENU_LOADED'
export const STORE_FETCHED_PAGE_MENU = 'STORE_FETCHED__PAGE_MENU'
export const PAGE_MENU_LOADED = 'PAGE_MENU_LOADED'
export const STORE_FETCHED_FOOTER_MENU = 'STORE_FETCHED_FOOTER_MENU'
export const FOOTER_MENU_LOADED = 'FOOTER_MENU_LOADED'

export const STORE_FETCHED_USERS = 'STORE_FETCHED_USERS'
export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const USERS_LOADED = 'USERS_LOADED'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'

export const STORE_FETCHED_CATEGORY = 'STORE_FETCHED_CATEGORY'
export const CATEGORY_LOADED = 'CATEGORY_LOADED'
